### ISSUE TITLE
Permission...?

### ISSUE THREAD

**Issue by xenreon** [HyperTeam/android_kernel_hyper_msm8916#4]
You do realize that you demading others to ask for permission to use this violates gpl right? lol

**Comment by phantom-1402** [comment]
Lmao
We should have kept the repo private then.....

**Comment by dev-harsh1998** [comment]
@xenreon say this here as well ! https://github.com/neobuddy89/shamu

**Comment by nathanchance** [comment]
@phantom-1402 @dev-harsh1998 wow you guys really believe you are above the GPL. You do realize that without the GPL, this wouldn't be possible right? I guarantee you most companies wouldn't ever release source. They'd keep everything internal. Go ahead, close source your stuff. You guys are better than the other 4000 contributors who agreed to the license when the contributed right?

**Comment by phantom-1402** [comment]
@nathanchance 
I believe that you took my comment some otherway.... We told to ask permission because there was a possibility of sources might not compile.... Its just a precaution... nothing else lol.... If we had to violate GPL
We would have never pushed that into public.... Lol
I hope i am cleared :)

**Comment by nathanchance** [comment]
@phantom-1402 thanks for the explanation lol, GPL violations are probably my only trigger point. Cheers!

**Comment by phantom-1402** [comment]
I know mate @nathanchance 👍 
It happens sometimes :p

Nvm 
Cheers!

**Comment by dev-harsh1998** [comment]
Well i am happy to see that things are clear now @nathanchance this source is WIP and for now it wont compile for arm64 builds so that precaution message was needed i hope everything is clear as of now, And i personally assure you that this source wont go private and would be available to all once compilation issues and other (arch specific)bugs are solved the and of-course  warning message will be removed
